### PR TITLE
Determine correct legal evolution stage for Formes

### LINKED ISSUE #142: [Bug] Pokémon evolved on the wrong level
**Describe the bug**
When enabling both “Do not use prematurely evolved Pokémon” and “Trainers Evolve their Pokémon”, trainer Pokémon can still appear at evolution stages that do not match their actual level, resulting in Pokémon that should not legally be evolved (or fully evolved) at that level.

This contradicts the intended behavior of the “Do not use prematurely evolved Pokémon” option, which should guarantee legal evolution stages based on level.
**See Additional context for more info**

**To Reproduce**
Load a compatible ROM.
Go to Trainer Pokémon settings.
Enable “Trainers Evolve their Pokémon”.
Enable “Do not use prematurely evolved Pokémon”.
Randomize the ROM.
Encounter trainer battles and observe Pokémon evolution stages.

**Expected behavior**
Trainer Pokémon should always be at a legal evolution stage for their actual level, regardless of evolution scaling or percentage settings, when “Do not use prematurely evolved Pokémon” is enabled.

No trainer Pokémon should appear evolved earlier than allowed by their natural evolution level.

**Screenshots**

Image

Image

Image

These examples do not match the levels at which these Pokémon evolve.

**Settings String + Seed**
If available, include the Settings String and Seed for the randomized ROM. These are shown during randomization and in any error+log files.
Settings String: N/A
Seed: N/A

**System (please complete the following information):**
Operating System: Windows 10 / Windows 11
Java Version: Java 17 (Temurin / OpenJDK)
Randomizer Version: UPR FVX v1.4.0

**Additional context**
It is possible that this behavior is related to the Fully Evolved level being effectively set to level 37 due to the evolution scaling settings, and that this behavior is technically working as intended. However, the resulting trainer Pokémon evolutions still feel inconsistent or unintuitive, as some Pokémon appear evolved at unusually low levels.

### PR DESCRIPTION
**Pull request by bergmaen**
Fix `Species.isLegalEvolutionAtLevel` and `Species.hasLegalEvolutionAtLevel` for 
* formes such as Megas that do not carry their evolution information by checking their base forme instead
* base formes with Alolan formes by checking their Alolan forme instead (e.g., Raichu in SM USUM)

Fixes #142

### CODE REVIEW

File: src/com/dabomstew/pkromio/gamedata/Species.java [hunk 1]
```diff
@@ -42,6 +42,7 @@ public class Species implements Comparable<Species> {
     private String formeSuffix = "";
     private Species baseForme = null;
     private int formeNumber = 0;
+    private Species alolanForme = null;
```
Comment (voliol) [inline src/com/dabomstew/pkromio/gamedata/Species.java]: Not a big fan of this attribute long-term. Having a pointer to a specific alt forme isn't pretty, and it doesn't account for Gen 8+ (and plenty of ROM hacks) having non-Alolan regional formes, with Meowth having both an Alolan and a Galarian forme, leading to troubles should those be supported... 
but since the Species have no way of getting *any* of their alt formes at the moment, without relying on a passed RomHandler, yeah this is the way to go 👍 .

File: test/test/com/dabomstew/pkromio/romhandlers/RomHandlerSpeciesStatsTest.java [hunk 2]
```diff
@@ -77,6 +80,22 @@ public String toString() {
         }
     }
 
+    @ParameterizedTest
+    @MethodSource("getRomNames")
+    public void baseFormeOfAlolanFormesHasCorrectAlolanForme(String romName) {
```
Comment (voliol) [inline test/test/com/dabomstew/pkromio/romhandlers/RomHandlerSpeciesStatsTest.java]: Good test

File: src/com/dabomstew/pkromio/gamedata/Species.java (hunk 1 above)
Comment (bergmaen) [reply src/com/dabomstew/pkromio/gamedata/Species.java]: Oh no, this definitely should not survive long term and especially the forme refactor. This really is just supposed to fix the bug for all **officially supported** ROMs. 
And that it does as far as I see. :crossed_fingers:

**Review by voliol — APPROVED** [review]
All looks good 👍
